### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joostlek** [kk7ds/uvcclient#7]
Hey 👋🏻,

I am currently looking into licensing within the Home Assistant project. Apparently this dependency isn't licensed. Could you please add an OSI approved license to this repository? It would help supporting the `uvc` integration in Home Assistant.

**Comment by joostlek** [comment]
![image](https://github.com/kk7ds/uvcclient/assets/7083755/d7a172ae-2e4a-4b10-8c3b-97ae3ef14f8c)
Apparently ~150 people are using it (stats can be x3 for a rough estimate because not everyone shares info)

**Comment by kk7ds** [comment]
Okay, shocking ;)

Can you just push a GPLv3 license file and the setup change (like from my other repo) and I'll try to merge and release both soon. The files already have GPLv3 headers on them.

**Comment by kk7ds** [comment]
Done here: https://github.com/kk7ds/uvcclient/releases/tag/0.11.1

I sort of feel the same about this as mficlient. I know some people are holding only UVC video and so I suspect there *are* really users for this, but it's so old, uvc is abandonware also, and it's been so long since I tested it. Probably best if someone that wants to keep this alive takes it over.
